#+title: System Specific Configuration

* Table of Contents
:PROPERTIES:
:TOC:       :include all :ignore this
:END:
:CONTENTS:
- [[#systems][Systems]]
  - [[#base-configuration][Base Configuration]]
  - [[#machines][Machines]]
    - [[#per-system-settings][Per-System Settings]]
  - [[#guts][guts]]
  - [[#buster][buster]]
  - [[#punchy][punchy]]
  - [[#cutman][cutman]]
- [[#system-settings-get][system-settings-get]]
:END:

* Systems

** Base Configuration

This base configuration is shared between all of the machines I manage.

@todo

** Machines

Machines are named with shortness and distinguishability in mind. Some of them have been around nearly a decade so I'm rather partial to them.

*** Per-System Settings

Some settings need to be customized on a per-system basis without tweaking individual configuration files. Thanks to =noweb= this is pretty easy to tweak.

@todo: define a getter function =cy/system-settings-get= to retrieve values appropriately.

#+begin_src emacs-lisp :tangle ~/.emacs.d/per-system-settings.el :noweb yes
(require 'map) ;; needed for map-merge

(setq cy/system-settings
  (map-merge
    'list
    '((desktop/dpi . 180)
      (desktop/background . "some-file.jpg")
      (emacs/dashboard-agenda-face-size . 100)
      (emacs/default-face-size . 100)
      (emacs/variable-face-size . 2.45)
      (emacs/fixed-face-size . 1.5))
    <<system-settings>>))
#+end_src

** guts

=guts= is my primary desktop machine. It runs 3 2560x1440 monitors. =guts= has two hard drives, one which boots =Arch Linux= and the other which boots =Windows 10=.

#+begin_src emacs-lisp :noweb-ref system-settings :noweb-sep
(when (equal system-name "guts")
  '((desktop/dpi . 109)
    (emacs/variable-face-size . 1.1)
    (emacs/fixed-face-size . 1.1)
    (emacs/default-face-size . 100)))

;; When booted into Windows
(when (equal system-name "GUTS")
  '((desktop/dpi . 109)
    (emacs/variable-face-size . 1.1)
    (emacs/fixed-face-size . 1.1)
    (emacs/default-face-size . 100)))

#+end_src

*NOTE*: The description of the monitor setup isn't accurate anymore. I've got a 49" Samsung 32:9 monitor now and a portrait one on the side, the setup isn't final so I'm not updating the text yet.

** buster

=buster= is a ThinkPad x201s that runs =Arch Linux=. This is a side machine that more or less acts as a backup when other machines are down for service or when I have a need to test out equipment in the network closet via a cabled interface. Most of the time it gets used for Music and Movie watching in the background.

*System Settings*

#+begin_src emacs-lisp :noweb-ref system-settings :noweb-sep
(when (equal system-name "buster")
  '((desktop/dpi . 90)
    (emacs/default-face-size . 110)
    (emacs/variable-face-size . 110)
    (emacs/fixed-face-size . 110)))
#+end_src


** punchy

=punchy= is a ThinkPad p43s that I use primarily for my day job, but has also become a go-to favorite generally. It runs =Arch Linux= and =Windows 10=. The screen is wonderful, but there are some HiDPI quirks that make using =i3= and =gtk= applications somewhat annoying.

I've been experimenting with using WSL2 to run Emacs and forward the X sessions out to =guts= or Windows 10 locally. It works pretty well.

*System Settings*

#+begin_src emacs-lisp :noweb-ref system-settings :noweb-sep
(when (equal system-name "punchy")
  '((desktop/dpi . 89)
    (emacs/default-face-size . 110)
    (emacs/variable-face-size . 110)
    (emacs/fixed-face-size . 110)))
;; When booted into Windows
(when (equal system-name "PUNCHY")
  '((desktop/dpi . 89)
    (emacs/variable-face-size . 1.1)
    (emacs/fixed-face-size . 1.1)
    (emacs/default-face-size . 100)))

#+end_src

** cutman

=cutman= is a Pixel 5. I've yet to get into figuring out how to use Emacs with it.

* =system-settings-get=

#+begin_src emacs-lisp :tangle ~/.emacs.d/per-system-settings.el :noweb yes
(defun cy/system-settings-get (setting)
 (alist-get setting cy/system-settings))
#+end_src
