icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#333333"
idle_fg = "#ffffff"
info_bg = "#05eafa"
info_fg = "#490e61"
good_bg = "#fa056f"
good_fg = "#ffffff"
warning_bg = "#fa056f"
warning_fg = "#ffffff"
critical_bg = "#fa1505"
critical_fg = "#ffffff"
separator = ""

# [[block]]
# block = "temperature"
# collapsed = false
# interval = 10
# format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "time"
interval = 60
format = "%a %R"
